apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiring-app
  labels:
    app: hiring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hiring-app
  template:
    metadata:
      labels:
        app: hiring-app
    spec:
      containers:
        - name: hiring-app
          image: imrankhanmohammad257/hiring-app:latest   # <= update this
          ports:
            - containerPort: 8080
