apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiring-app
  template:
    metadata:
      labels:
        app: hiring-app
    spec:
      containers:
        - name: hiring-app
          image: imrankhanmohammad257/hiring-app:latest
          imagePullPolicy: Always   # ✅ force K8s to pull new latest image
          ports:
            - containerPort: 8080
